### ISSUE TITLE
Peer Review - Julian

### ISSUE THREAD

**Issue by juliandecloe** [norakramer1/web-app-from-scratch-2122#1]
Je kan images uit de API kleiner laden met: artObjects.webImage.url.slice(0, -3)+"=s1000"

Je moet nog even kijken of je de detailed API al meteen wil laden. 

Je plaatst comments met // _content_
Voor 1 regel comments is dat prettig, maar als je meerdere regels in een comment wil zetten kun je net als in css /* _content_ */ gebruiken.

Je kan een const maken van detailed.artObject en die gebruiken ipv telkens detailed.artObject te typen. 

Voor de rest heb ik er niks op aan te merken!

**Comment by norakramer1** [comment]
- Images zijn kleiner gemaakt
- detailed API moet ik meteen al laden ivm jaar van het schilderij
- Ga ik voortaan doen :)
- Goeie ik ga het implementeren
