### ISSUE TITLE
Code review best practices

### ISSUE THREAD

**Issue by Joepkl** [norakramer1/web-app-from-scratch-2122#5]
1.
Split fetch url in separate chunks
For readability and efficient code. With this aproach parts of the url can be reused for future fetches.

Je zou dus de rijks API kunnen opsplitsen ipv de hele link in een const te zetten.  Bijvoorbeeld 
const cors = 'https://cors-anywhere.herokuapp.com/';
const endpoint = 'https://api.anywhere.com';
const key = '42';
const url = `${cors}`${endpoint}/?key=${key};

fetch (url)

2. Netjes alle functions in modules opgesplitst!

3. Ik weet niet of het aan mij ligt maar er wordt geen content ingeladen ik zie alleen de skeleton state. Ook krijg ik een 404 error als ik zoek naar kunstwerken.

**Comment by norakramer1** [comment]
fetch url opsplitsen staat in de to-do.

de link doet het weer
